In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv(r'D:\ANJANA\Imarticus Notes\Capstone project 1\train.csv')
test_data = pd.read_csv(r'D:\ANJANA\Imarticus Notes\Capstone project 1\test.csv')

In [3]:
train_data.head()

UniqueID  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    420825             50578       58400  89.55         67        22807   
1    537409             47145       65550  73.23         67        22807   
2    417566             53278       61360  89.63         67        22807   
3    624493             57513       66113  88.48         67        22807   
4    539055             52378       60300  88.39         67        22807   

   manufacturer_id  Current_pincode_ID Date.of.Birth Employment.Type  ...  \
0               45                1441      01-01-84        Salaried  ...   
1               45                1502      31-07-85   Self employed  ...   
2               45                1497      24-08-85   Self employed  ...   
3               45                1501      30-12-93   Self employed  ...   
4               45                1495      09-12-77   Self employed  ...   

  SEC.SANCTIONED.AMOUNT  SEC.DISBURSED.AMOUNT  PRIMARY.INSTAL.AMT  \
0                     0                     0                   0   
1                     0                     0                1991   
2                     0                     0                   0   
3                     0                     0                  31   
4                     0                     0                   0   

   SEC.INSTAL.AMT  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  AVERAGE.ACCT.AGE  \
0                                    0         0yrs 0mon   
1                                    1        1yrs 11mon   
2                                    0         0yrs 0mon   
3                                    0         0yrs 8mon   
4                                    0         0yrs 0mon   

   CREDIT.HISTORY.LENGTH  NO.OF_INQUIRIES  loan_default  
0              0yrs 0mon                0             0  
1             1yrs 11mon                0             1  
2              0yrs 0mon                0             0  
3              1yrs 3mon                1             1  
4              0yrs 0mon                1             1  

[5 rows x 41 columns]

In [4]:
test_data.head()

UniqueID  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    655269             53478       63558  86.54         67        22807   
1    723482             55513       63163  89.45         67        22807   
2    758529             65282       84320  79.93         78        23135   
3    763449             46905       63896  76.58         78        17014   
4    708663             51428       63896  86.08         78        17014   

   manufacturer_id  Current_pincode_ID Date.of.Birth Employment.Type  ...  \
0               45                1497      01-01-74        Salaried  ...   
1               45                1497      20-05-85   Self employed  ...   
2               86                2071      14-10-95        Salaried  ...   
3               45                2070      01-06-73   Self employed  ...   
4               45                2069      01-06-72        Salaried  ...   

  SEC.CURRENT.BALANCE  SEC.SANCTIONED.AMOUNT  SEC.DISBURSED.AMOUNT  \
0                   0                      0                     0   
1                   0                      0                     0   
2                   0                      0                     0   
3                   0                      0                     0   
4                   0                      0                     0   

   PRIMARY.INSTAL.AMT  SEC.INSTAL.AMT  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0                   0               0                             0   
1                5605               0                             1   
2                   0               0                             0   
3                   0               0                             0   
4                   0               0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  AVERAGE.ACCT.AGE  \
0                                    0         0yrs 0mon   
1                                    0         0yrs 8mon   
2                                    0         0yrs 0mon   
3                                    0         2yrs 5mon   
4                                    0         0yrs 0mon   

   CREDIT.HISTORY.LENGTH  NO.OF_INQUIRIES  
0              0yrs 0mon                0  
1              1yrs 0mon                1  
2              0yrs 0mon                0  
3              2yrs 5mon                0  
4              0yrs 0mon                0  

[5 rows x 40 columns]

In [5]:
train_data.columns = [i.lower().replace('.','_') for i in train_data.columns]
test_data.columns = [i.lower().replace('.','_') for i in test_data.columns]

In [6]:
train_data.head()

uniqueid  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    420825             50578       58400  89.55         67        22807   
1    537409             47145       65550  73.23         67        22807   
2    417566             53278       61360  89.63         67        22807   
3    624493             57513       66113  88.48         67        22807   
4    539055             52378       60300  88.39         67        22807   

   manufacturer_id  current_pincode_id date_of_birth employment_type  ...  \
0               45                1441      01-01-84        Salaried  ...   
1               45                1502      31-07-85   Self employed  ...   
2               45                1497      24-08-85   Self employed  ...   
3               45                1501      30-12-93   Self employed  ...   
4               45                1495      09-12-77   Self employed  ...   

  sec_sanctioned_amount  sec_disbursed_amount  primary_instal_amt  \
0                     0                     0                   0   
1                     0                     0                1991   
2                     0                     0                   0   
3                     0                     0                  31   
4                     0                     0                   0   

   sec_instal_amt  new_accts_in_last_six_months  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   delinquent_accts_in_last_six_months  average_acct_age  \
0                                    0         0yrs 0mon   
1                                    1        1yrs 11mon   
2                                    0         0yrs 0mon   
3                                    0         0yrs 8mon   
4                                    0         0yrs 0mon   

   credit_history_length  no_of_inquiries  loan_default  
0              0yrs 0mon                0             0  
1             1yrs 11mon                0             1  
2              0yrs 0mon                0             0  
3              1yrs 3mon                1             1  
4              0yrs 0mon                1             1  

[5 rows x 41 columns]

In [7]:
test_data.head()

uniqueid  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    655269             53478       63558  86.54         67        22807   
1    723482             55513       63163  89.45         67        22807   
2    758529             65282       84320  79.93         78        23135   
3    763449             46905       63896  76.58         78        17014   
4    708663             51428       63896  86.08         78        17014   

   manufacturer_id  current_pincode_id date_of_birth employment_type  ...  \
0               45                1497      01-01-74        Salaried  ...   
1               45                1497      20-05-85   Self employed  ...   
2               86                2071      14-10-95        Salaried  ...   
3               45                2070      01-06-73   Self employed  ...   
4               45                2069      01-06-72        Salaried  ...   

  sec_current_balance  sec_sanctioned_amount  sec_disbursed_amount  \
0                   0                      0                     0   
1                   0                      0                     0   
2                   0                      0                     0   
3                   0                      0                     0   
4                   0                      0                     0   

   primary_instal_amt  sec_instal_amt  new_accts_in_last_six_months  \
0                   0               0                             0   
1                5605               0                             1   
2                   0               0                             0   
3                   0               0                             0   
4                   0               0                             0   

   delinquent_accts_in_last_six_months  average_acct_age  \
0                                    0         0yrs 0mon   
1                                    0         0yrs 8mon   
2                                    0         0yrs 0mon   
3                                    0         2yrs 5mon   
4                                    0         0yrs 0mon   

   credit_history_length  no_of_inquiries  
0              0yrs 0mon                0  
1              1yrs 0mon                1  
2              0yrs 0mon                0  
3              2yrs 5mon                0  
4              0yrs 0mon                0  

[5 rows x 40 columns]

## No of records in train and test data

In [8]:
print(train_data.shape)
print(test_data.shape)

(233154, 41)
(112392, 40)


## Data Cleaning 

In [9]:
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   uniqueid                             233154 non-null  int64  
 1   disbursed_amount                     233154 non-null  int64  
 2   asset_cost                           233154 non-null  int64  
 3   ltv                                  233154 non-null  float64
 4   branch_id                            233154 non-null  int64  
 5   supplier_id                          233154 non-null  int64  
 6   manufacturer_id                      233154 non-null  int64  
 7   current_pincode_id                   233154 non-null  int64  
 8   date_of_birth                        233154 non-null  object 
 9   employment_type                      225493 non-null  object 
 10  disbursaldate                        233154 non-null  object 
 11  state_id     

In [10]:
print(train_data.isna().sum())

uniqueid                                  0
disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
current_pincode_id                        0
date_of_birth                             0
employment_type                        7661
disbursaldate                             0
state_id                                  0
employee_code_id                          0
mobileno_avl_flag                         0
aadhar_flag                               0
pan_flag                                  0
voterid_flag                              0
driving_flag                              0
passport_flag                             0
perform_cns_score                         0
perform_cns_score_description             0
pri_no_of_accts                           0
pri_active_accts                

In [11]:
print(test_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112392 entries, 0 to 112391
Data columns (total 40 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   uniqueid                             112392 non-null  int64  
 1   disbursed_amount                     112392 non-null  int64  
 2   asset_cost                           112392 non-null  int64  
 3   ltv                                  112392 non-null  float64
 4   branch_id                            112392 non-null  int64  
 5   supplier_id                          112392 non-null  int64  
 6   manufacturer_id                      112392 non-null  int64  
 7   current_pincode_id                   112392 non-null  int64  
 8   date_of_birth                        112392 non-null  object 
 9   employment_type                      108949 non-null  object 
 10  disbursaldate                        112392 non-null  object 
 11  state_id     

In [12]:
print(test_data.isna().sum())

uniqueid                                  0
disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
current_pincode_id                        0
date_of_birth                             0
employment_type                        3443
disbursaldate                             0
state_id                                  0
employee_code_id                          0
mobileno_avl_flag                         0
aadhar_flag                               0
pan_flag                                  0
voterid_flag                              0
driving_flag                              0
passport_flag                             0
perform_cns_score                         0
perform_cns_score_description             0
pri_no_of_accts                           0
pri_active_accts                

In [13]:
train_data['employment_type'].unique()

array(['Salaried', 'Self employed', nan], dtype=object)

In [14]:
train_data['employment_type'] = train_data['employment_type'].map({'Salaried':0, 'Self employed':1, np.nan: 2})
test_data['employment_type'] = test_data['employment_type'].map({'Salaried':0, 'Self employed':1, np.nan: 2})

In [15]:
#train_data.loc[(train_data['employment_type'] == 1) & (train_data['loan_default'] == 1), ['loan_default', 'state_id', 'employment_type', 'current_balance', 'perform_cns_score', 'credit_history_length', 'average_acct_age']]

In [16]:
train_data['credit_history_length'].max()

'9yrs 9mon'

In [17]:
#Now, we need to deal with the date columns i.e., date_of_birth, disbursaldate

In [18]:
# Converting the date_of_birth and disbursaldate into DateTime Format

In [19]:
train_data['date_of_birth'] =  pd.to_datetime(train_data['date_of_birth'])
test_data['date_of_birth'] =  pd.to_datetime(test_data['date_of_birth'])

train_data['disbursaldate'] =  pd.to_datetime(train_data['disbursaldate'])
test_data['disbursaldate'] =  pd.to_datetime(test_data['disbursaldate'])

In [20]:
test_data['date_of_birth'].head()

0   1974-01-01
1   1985-05-20
2   1995-10-14
3   1973-01-06
4   2072-01-06
Name: date_of_birth, dtype: datetime64[ns]

In [21]:
now = pd.Timestamp('now')
now

Timestamp('2023-12-24 08:58:59.482497')

In [22]:
train_data['date_of_birth'] = train_data['date_of_birth'].where(train_data['date_of_birth'] < now, train_data['date_of_birth'] - np.timedelta64(100, 'Y'))
train_data['age']=(now- train_data['date_of_birth']).astype('<m8[Y]').astype(int)
train_data=train_data.drop('date_of_birth',axis=1)

In [23]:
train_data['age'].head()

0    39
1    38
2    38
3    29
4    46
Name: age, dtype: int32

In [24]:
test_data['date_of_birth'] = test_data['date_of_birth'].where(test_data['date_of_birth'] < now, test_data['date_of_birth'] - np.timedelta64(100, 'Y'))
test_data['age']=(now- test_data['date_of_birth']).astype('<m8[Y]').astype(int)
test_data=test_data.drop('date_of_birth',axis=1)

In [25]:
test_data['age'].head()

0    49
1    38
2    28
3    50
4    51
Name: age, dtype: int32

In [26]:
train_data['disbursaldate'].head()

0   2018-03-08
1   2018-09-26
2   2018-01-08
3   2018-10-26
4   2018-09-26
Name: disbursaldate, dtype: datetime64[ns]

In [27]:
train_data['disbursal_months_passed']=((now -train_data['disbursaldate'])/np.timedelta64(1,'M')).astype(int)
train_data['disbursal_months_passed'].head()

0    69
1    62
2    71
3    61
4    62
Name: disbursal_months_passed, dtype: int32

In [28]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 42 columns):
 #   Column                               Non-Null Count   Dtype         
---  ------                               --------------   -----         
 0   uniqueid                             233154 non-null  int64         
 1   disbursed_amount                     233154 non-null  int64         
 2   asset_cost                           233154 non-null  int64         
 3   ltv                                  233154 non-null  float64       
 4   branch_id                            233154 non-null  int64         
 5   supplier_id                          233154 non-null  int64         
 6   manufacturer_id                      233154 non-null  int64         
 7   current_pincode_id                   233154 non-null  int64         
 8   employment_type                      233154 non-null  int64         
 9   disbursaldate                        233154 non-null  datetime64[ns]
 

In [29]:
test_data['disbursal_months_passed']=((now - test_data['disbursaldate'])/np.timedelta64(1,'M')).astype(int)
test_data['disbursal_months_passed'].head()

0    69
1    61
2    60
3    60
4    61
Name: disbursal_months_passed, dtype: int32

In [30]:
train_data = train_data.drop('disbursaldate',axis=1)
test_data = test_data.drop('disbursaldate',axis=1)

In [31]:
# let us convert average_acct_age and credit_history_length into months 

In [32]:
train_data['average_acct_age'].head()

0     0yrs 0mon
1    1yrs 11mon
2     0yrs 0mon
3     0yrs 8mon
4     0yrs 0mon
Name: average_acct_age, dtype: object

In [33]:
train_data["average_acct_age"]=train_data["average_acct_age"].apply(lambda x:(int((x.split("y"))[0])*12)+(int((x.split())[1].split("m")[0])))
train_data["credit_history_length"]=train_data["credit_history_length"].apply(lambda x:(int((x.split("y"))[0])*12)+(int((x.split())[1].split("m")[0])))

In [34]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   uniqueid                             233154 non-null  int64  
 1   disbursed_amount                     233154 non-null  int64  
 2   asset_cost                           233154 non-null  int64  
 3   ltv                                  233154 non-null  float64
 4   branch_id                            233154 non-null  int64  
 5   supplier_id                          233154 non-null  int64  
 6   manufacturer_id                      233154 non-null  int64  
 7   current_pincode_id                   233154 non-null  int64  
 8   employment_type                      233154 non-null  int64  
 9   state_id                             233154 non-null  int64  
 10  employee_code_id                     233154 non-null  int64  
 11  mobileno_avl_

In [35]:
train_data[['perform_cns_score_description','perform_cns_score']].head()

perform_cns_score_description  perform_cns_score
0   No Bureau History Available                  0
1                 I-Medium Risk                598
2   No Bureau History Available                  0
3              L-Very High Risk                305
4   No Bureau History Available                  0

In [36]:
train_data['perform_cns_score'].max(), train_data['perform_cns_score'].min()

(890, 0)

In [37]:
train_data[train_data['perform_cns_score'] == 890]['perform_cns_score_description']

11125     A-Very Low Risk
100297    A-Very Low Risk
195585    A-Very Low Risk
211350    A-Very Low Risk
Name: perform_cns_score_description, dtype: object

In [38]:
train_data['perform_cns_score_description'].value_counts()

No Bureau History Available                                116950
C-Very Low Risk                                             16045
A-Very Low Risk                                             14124
D-Very Low Risk                                             11358
B-Very Low Risk                                              9201
M-Very High Risk                                             8776
F-Low Risk                                                   8485
K-High Risk                                                  8277
H-Medium Risk                                                6855
E-Low Risk                                                   5821
I-Medium Risk                                                5557
G-Low Risk                                                   3988
Not Scored: Sufficient History Not Available                 3765
J-High Risk                                                  3748
Not Scored: Not Enough Info available on the customer        3672
Not Scored

In [39]:
def catogorizing(i):
    if i<300:
        return 0
    elif (i>=300) and (i<=350):
        return 1
    elif (i>350) and (i<=570):
        return 2
    elif (i>570) and (i<=630):
        return 3
    elif (i>630) and (i<=705):
        return 4
    else:
        return 5

In [40]:
train_data['perform_cns_score_description'] = train_data['perform_cns_score'].apply(catogorizing)

In [41]:
train_data['perform_cns_score_description'].head()

0    0
1    3
2    0
3    1
4    0
Name: perform_cns_score_description, dtype: int64

In [42]:
train_data['perform_cns_score_description'].value_counts()

0    129785
5     50728
4     18294
3     12412
2     12025
1      9910
Name: perform_cns_score_description, dtype: int64

In [43]:
test_data['perform_cns_score_description'] = test_data['perform_cns_score'].apply(catogorizing)

In [44]:
train_data['employment_type'].unique()

array([0, 1, 2], dtype=int64)

In [45]:
train_data['sec_no_of_accts'].head()

0    0
1    0
2    0
3    0
4    0
Name: sec_no_of_accts, dtype: int64

In [46]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   uniqueid                             233154 non-null  int64  
 1   disbursed_amount                     233154 non-null  int64  
 2   asset_cost                           233154 non-null  int64  
 3   ltv                                  233154 non-null  float64
 4   branch_id                            233154 non-null  int64  
 5   supplier_id                          233154 non-null  int64  
 6   manufacturer_id                      233154 non-null  int64  
 7   current_pincode_id                   233154 non-null  int64  
 8   employment_type                      233154 non-null  int64  
 9   state_id                             233154 non-null  int64  
 10  employee_code_id                     233154 non-null  int64  
 11  mobileno_avl_

In [47]:
train_data['no_of_accts']=train_data['pri_no_of_accts']+train_data['sec_no_of_accts']
train_data['active_accts']=train_data['pri_active_accts']+train_data['sec_active_accts']
train_data['overdue_accts']=train_data['pri_overdue_accts']+train_data['sec_overdue_accts']
train_data['current_balance']=train_data['pri_current_balance']+train_data['sec_current_balance']
train_data['sanctioned_amount']=train_data['pri_sanctioned_amount']+train_data['sec_sanctioned_amount']
train_data['disbursed_amount']=train_data['pri_disbursed_amount']+train_data['sec_disbursed_amount']
train_data['instal_amt']=train_data['primary_instal_amt']+train_data['sec_instal_amt']

train_data=train_data.drop(['pri_no_of_accts', 'sec_no_of_accts', 'pri_active_accts', 'sec_active_accts', 'pri_overdue_accts', 'sec_overdue_accts', 'pri_current_balance', 'sec_current_balance', 'pri_sanctioned_amount', 'sec_sanctioned_amount', 'pri_disbursed_amount', 'sec_disbursed_amount', 'primary_instal_amt', 'sec_instal_amt'],axis=1)


In [48]:
test_data['no_of_accts']=test_data['pri_no_of_accts']+test_data['sec_no_of_accts']
test_data['active_accts']=test_data['pri_active_accts']+test_data['sec_active_accts']
test_data['overdue_accts']=test_data['pri_overdue_accts']+test_data['sec_overdue_accts']
test_data['current_balance']=test_data['pri_current_balance']+test_data['sec_current_balance']
test_data['sanctioned_amount']=test_data['pri_sanctioned_amount']+test_data['sec_sanctioned_amount']
test_data['disbursed_amount']=test_data['pri_disbursed_amount']+test_data['sec_disbursed_amount']
test_data['instal_amt']=test_data['primary_instal_amt']+test_data['sec_instal_amt']

test_data=test_data.drop(['pri_no_of_accts', 'sec_no_of_accts', 'pri_active_accts', 'sec_active_accts', 'pri_overdue_accts', 'sec_overdue_accts', 'pri_current_balance', 'sec_current_balance', 'pri_sanctioned_amount', 'sec_sanctioned_amount', 'pri_disbursed_amount', 'sec_disbursed_amount', 'primary_instal_amt', 'sec_instal_amt'],axis=1)

In [49]:
test_data.shape, train_data.shape

((112392, 32), (233154, 33))

In [50]:
train_data.columns[train_data.columns.str.contains("id")]

Index(['uniqueid', 'branch_id', 'supplier_id', 'manufacturer_id',
       'current_pincode_id', 'state_id', 'employee_code_id', 'voterid_flag'],
      dtype='object')

In [51]:
test_data.columns[test_data.columns.str.contains("id")]

Index(['uniqueid', 'branch_id', 'supplier_id', 'manufacturer_id',
       'current_pincode_id', 'state_id', 'employee_code_id', 'voterid_flag'],
      dtype='object')

In [52]:
#Dropping the unnecessary columns
train_data = train_data.drop(['uniqueid', 'branch_id', 'supplier_id', 'manufacturer_id','current_pincode_id', 'state_id', 'employee_code_id'],axis=1)
test_data = test_data.drop(['uniqueid', 'branch_id', 'supplier_id', 'manufacturer_id','current_pincode_id', 'state_id', 'employee_code_id'],axis=1)

## Training the model 

In [53]:
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

In [54]:
y = train_data['loan_default']
x = train_data.drop(['loan_default'],axis=1)

In [55]:
y.value_counts()/len(y)*100

0    78.292888
1    21.707112
Name: loan_default, dtype: float64

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size = 0.20, random_state = 49)
print("Shape of train :", x_train.shape)
print("Shape of test :", x_test.shape)

Shape of train : (186523, 25)
Shape of test : (46631, 25)


In [57]:
y_train.value_counts()/len(y_train)*100

0    78.357629
1    21.642371
Name: loan_default, dtype: float64

In [58]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)

In [59]:
train_x.shape,test_x.shape

((186523, 25), (46631, 25))

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
sc= StandardScaler()
sc.fit(train_x)

StandardScaler()

In [62]:
train_x_scale=pd.DataFrame(sc.transform(train_x),columns=train_x.columns,index=train_x.index)
test_x_scale=pd.DataFrame(sc.transform(test_x),columns=train_x.columns,index=test_x.index)

In [63]:
train_x_scale.isna().sum()

disbursed_amount                       0
asset_cost                             0
ltv                                    0
employment_type                        0
mobileno_avl_flag                      0
aadhar_flag                            0
pan_flag                               0
voterid_flag                           0
driving_flag                           0
passport_flag                          0
perform_cns_score                      0
perform_cns_score_description          0
new_accts_in_last_six_months           0
delinquent_accts_in_last_six_months    0
average_acct_age                       0
credit_history_length                  0
no_of_inquiries                        0
age                                    0
disbursal_months_passed                0
no_of_accts                            0
active_accts                           0
overdue_accts                          0
current_balance                        0
sanctioned_amount                      0
instal_amt      

### Logistic Regression 

In [64]:
logmodel = LogisticRegression() 
logmodel.fit(train_x_scale,train_y)
logpred = logmodel.predict(test_x_scale)

In [65]:
print(confusion_matrix(test_y, logpred))
print(round(accuracy_score(test_y, logpred),2)*100)

[[36559    55]
 [ 9975    42]]
78.0


In [66]:
lr_confusion = confusion_matrix(test_y, logpred)
lr_accuracy = accuracy_score(test_y, logpred)
lr_f1score = f1_score(test_y, logpred)
lr_precision = precision_score(test_y, logpred)
lr_recall = recall_score(test_y, logpred)
print('Accuracy:', lr_accuracy)
print('Confusion matrix:\n', lr_confusion)
print('Precision score:\n', lr_precision)
print('recall:\n', lr_recall)
print('f1 score:\n',lr_f1score)

Accuracy: 0.7849070360918702
Confusion matrix:
 [[36559    55]
 [ 9975    42]]
Precision score:
 0.4329896907216495
recall:
 0.0041928721174004195
f1 score:
 0.008305319359303936


### AdaBoost

In [67]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [68]:
# Fit a base estimator on the training set
base_estimator = DecisionTreeClassifier(max_depth=1)
base_estimator.fit(train_x_scale,train_y)

DecisionTreeClassifier(max_depth=1)

In [69]:
# Fit an AdaBoost model on the training set
adaboost = AdaBoostClassifier(base_estimator=base_estimator, n_estimators=50, learning_rate=1.0, random_state=42)
adaboost.fit(train_x_scale,train_y)
# Evaluate the performance of the model on the test set
y_pred = adaboost.predict(test_x_scale)
ad_accuracy = accuracy_score(test_y, y_pred)
ad_confusion = confusion_matrix(test_y, y_pred)
ad_precision = precision_score(test_y,y_pred)
ad_f1score = f1_score(test_y,y_pred)
ad_recall = recall_score(test_y,y_pred)
print('Accuracy:', ad_accuracy)
print('Confusion matrix:\n', ad_confusion)
print('Precision score:\n', ad_precision)
print('recall:\n', ad_recall)
print('f1 score:\n',ad_f1score)

C:\Users\anjan\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Accuracy: 0.7849284810533765
Confusion matrix:
 [[36519    95]
 [ 9934    83]]
Precision score:
 0.46629213483146065
recall:
 0.008285913946291305
f1 score:
 0.01628249141736145


### KNN

In [70]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(train_x_scale, train_y)
y_pred = model.predict(test_x_scale)

knn_accuracy = accuracy_score(test_y, y_pred)
knn_confusion = confusion_matrix(test_y, y_pred)
knn_precision = precision_score(test_y,y_pred)
knn_f1_score = f1_score(test_y,y_pred)
knn_recall = recall_score(test_y,y_pred)
print('Accuracy:', knn_accuracy)
print('Confusion matrix:\n', knn_confusion)
print('Precision:\n', knn_precision)
print('recall:\n', knn_recall)
print('f1 score:\n',knn_f1_score)

Accuracy: 0.7442259441144303
Confusion matrix:
 [[33459  3155]
 [ 8772  1245]]
Precision:
 0.28295454545454546
recall:
 0.12428870919436957
f1 score:
 0.1727127696469446


### Naïve Bayes

In [71]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(train_x_scale, train_y)
y_pred = model.predict(test_x_scale)

nb_accuracy = accuracy_score(test_y, y_pred)
nb_confusion = confusion_matrix(test_y, y_pred)
nb_precision = precision_score(test_y,y_pred)
nb_f1_score = f1_score(test_y,y_pred)
nb_recall = recall_score(test_y,y_pred)
print('Accuracy:', nb_accuracy)
print('Confusion matrix:\n', nb_confusion)
print('Precision:\n', nb_precision)
print('recall:\n', nb_recall)
print('f1 score:\n',nb_f1_score)

Accuracy: 0.7742060003002295
Confusion matrix:
 [[35772   842]
 [ 9687   330]]
Precision:
 0.2815699658703072
recall:
 0.03294399520814615
f1 score:
 0.05898650460273482


In [72]:
### Random Forest

In [73]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import auc
from sklearn.ensemble import RandomForestClassifier

In [74]:
#model=RandomForestClassifier(n_estimators=300,max_features=0.9,max_depth=30,min_samples_split=3,min_samples_leaf=50, n_jobs=-1)

In [75]:
#model.fit(train_x_scale, train_y)

In [76]:
#train_data.shape

In [77]:
#y_pred = model.predict(test_x_scale)

rf_accuracy = accuracy_score(test_y, y_pred)
rf_confusion = confusion_matrix(test_y, y_pred)
rf_precision = precision_score(test_y,y_pred)
rf_f1_score = f1_score(test_y,y_pred)
rf_recall = recall_score(test_y,y_pred)
print('Accuracy:', rf_accuracy)
print('Confusion matrix:\n', rf_confusion)
print('Precision:\n', rf_precision)
print('recall:\n', rf_recall)
print('f1 score:\n',rf_f1_score)

Accuracy: 0.7742060003002295
Confusion matrix:
 [[35772   842]
 [ 9687   330]]
Precision:
 0.2815699658703072
recall:
 0.03294399520814615
f1 score:
 0.05898650460273482


In [78]:
model=RandomForestClassifier(n_estimators=300,max_features=0.9,max_depth=30,min_samples_split=3,min_samples_leaf=50, n_jobs=-1)

In [79]:
model.fit(train_x_scale, train_y)

RandomForestClassifier(max_depth=30, max_features=0.9, min_samples_leaf=50,
                       min_samples_split=3, n_estimators=300, n_jobs=-1)

In [80]:
y_pred = model.predict(test_x_scale)

In [81]:
rf_accuracy = accuracy_score(test_y, y_pred)
rf_confusion = confusion_matrix(test_y, y_pred)
rf_precision = precision_score(test_y,y_pred)
rf_f1_score = f1_score(test_y,y_pred)
rf_recall = recall_score(test_y,y_pred)
print('Accuracy:', rf_accuracy)
print('Confusion matrix:\n', rf_confusion)
print('Precision:\n', rf_precision)
print('recall:\n', rf_recall)
print('f1 score:\n',rf_f1_score)

Accuracy: 0.7854860500525401
Confusion matrix:
 [[36561    53]
 [ 9950    67]]
Precision:
 0.5583333333333333
recall:
 0.006688629330138764
f1 score:
 0.013218901055539113


In [82]:
results_df = pd.DataFrame({
    'Model': ['Logistic Regression','RF', 'AdaBoost', 'Naive Bayes', 'KNN'],
    'Accuracy': [lr_accuracy,rf_accuracy, ad_accuracy, nb_accuracy, knn_accuracy],
    'Precision': [lr_precision , rf_precision, ad_precision , nb_precision, knn_precision],
    'Recall': [lr_recall,rf_recall, ad_recall, nb_recall, knn_recall],
    'F1 Score': [lr_f1score,rf_f1_score, ad_f1score , nb_f1_score, knn_f1_score]
})

In [83]:
best_model = results_df.loc[results_df['F1 Score'].idxmax(), 'Model']
print(f"The best model is {best_model} with an F1 score of {results_df['F1 Score'].max(): 3f}")

The best model is KNN with an F1 score of  0.172713
